#!/bin/bash


function restart_podman(){

    if [ ! "$1" ]; then
        echo "Please specify container in order to restart"
        exit 1
    
    else

        echo -e "Restarting container $1 \n"
        podman restart $1
    fi

}


restart_podman $1